//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casos
    {
        public int IDCaso { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string País { get; set; }
        public string Ciudad { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Comentario { get; set; }
        public System.DateTime FechaContagio { get; set; }
    }
}
