//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public int IDNew { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Resumen { get; set; }
        public byte[] Foto { get; set; }
        public string Contenido { get; set; }
    }
}
